### ISSUE TITLE
Will the BEAT dataset be released?

### ISSUE THREAD

**Issue by kingmpw2015** [PantoMatrix/PantoMatrix#1]
hi,
great job!
BEAT: A Large-Scale Semantic and Emotional Multi-Modal Dataset for Conversational Gestures Synthesis 
It is said in the paper that the data, code and model will be released for research. So when will the data be released?

**Comment by H-Liu1997** [comment]
hi, 

The raw data already released, you may download them from: https://drive.google.com/drive/folders/1CVyJOp3G_A9l1N_CsKdHgXQfB4pXhG8c?usp=sharing

We are also rendering videos for all data:
https://drive.google.com/drive/folders/1ghZ7_4LkCyM_IZxTElzAwPzGheLrBGBu?usp=sharing

we are working on the final double-check of annotations and they will be released around Oct. 1st.

Thank you very much for your understanding!
Feel free to let us know if you have any further concerns.

**Comment by kingmpw2015** [comment]
> 

thanks a lot
