### ISSUE TITLE
Data download problem

### ISSUE THREAD

**Issue by rainofmine** [PantoMatrix/PantoMatrix#10]
Could you provide a compressed file of all data? I found some files always missing when I download the decompressed  data from the google drive link.

**Comment by H-Liu1997** [comment]
Sorry for the inconvenience, you may download data for each modal separately in this [zip link](https://drive.google.com/drive/folders/1EKuWH8q178QOtFUYaNohdkZbBHQYAmhL)

**Comment by abcyzj** [comment]
> Sorry for the inconvenience, you may download data for each modal separately in this [zip link](https://drive.google.com/drive/folders/1EKuWH8q178QOtFUYaNohdkZbBHQYAmhL)

I find that there are some files missing in the `beat_text.zip`, `beat_emotion.zip` and `beat_semantic.zip` files. Could you please fix that?

**Comment by H-Liu1997** [comment]
@abcyzj  I updated all raw English data (motion-audio-facial-text) in the above link. It contains all text information. Please try to use it.

**Comment by H-Liu1997** [comment]
@abcyzj you may also download all semantic annotation for english data, and all emotion labels for self-talk part now, please note that all data in conversation part  are labeled as neutral now. Thanks!

**Comment by abcyzj** [comment]
Thank you!

**Comment by SoltixUS** [comment]
> Sorry for the inconvenience, you may download data for each modal separately in this [zip link](https://drive.google.com/drive/folders/1EKuWH8q178QOtFUYaNohdkZbBHQYAmhL)

The Google Drive URL is broken, can you update it @H-Liu1997 ? I tried downloading the dataset via hugging face but quickly reached its download rate limit.
