### ISSUE TITLE
Demo of EMAGE

### ISSUE THREAD

**Issue by jiangzhengkai** [PantoMatrix/PantoMatrix#101]
Thanks for your great work. Would you release the demo for inference?

**Comment by H-Liu1997** [comment]
Thanks for the interest of EMAGE, we release the readme of EMAGE at:

https://github.com/PantoMatrix/PantoMatrix/blob/main/scripts/EMAGE_2024/readme.md

You could found the pretrained models, training and inference scripts now:)

**Comment by zzhat0706** [comment]
Thanks for the interest of EMAGE, we now release the colab demo.
please check this link.
https://colab.research.google.com/drive/1AINafluW6Ba5-KYN_L43eyFK0zRklMvr?usp=sharing
