### ISSUE TITLE
ModuleNotFoundError: No module named 'dataloaders.pymo'

### ISSUE THREAD

**Issue by jiangzhengkai** [PantoMatrix/PantoMatrix#102]
Hi, would you upload your pymo. I got this error directly runing yout EMAGE code

**Comment by H-Liu1997** [comment]
Thanks for the interest of EMAGE, we release the readme of EMAGE at:

https://github.com/PantoMatrix/PantoMatrix/blob/main/scripts/EMAGE_2024/readme.md

You could found the pretrained models, training and inference scripts now:)
