### ISSUE TITLE
emotion 在beat-x里面是没了吗？beat里面是有的。

### ISSUE THREAD

**Issue by GuangtaoLyu** [PantoMatrix/PantoMatrix#104]
emotion 在beat-x里面是没了吗？beat里面是有的。还是说还会继续更新。

**Comment by H-Liu1997** [comment]
同学你好，BEATX 和 BEAT是一套数据，不同的表现形式，所以beat里面的emotion 标签可以直接在beatx中使用。

**Comment by GuangtaoLyu** [comment]
好的，多谢分享。




Guangtao&nbsp;Lyu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantoMatrix/PantoMatrix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月22日(星期一) 晚上6:16
***@***.***&gt;;
抄送:&nbsp;"Guangtao ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantoMatrix/PantoMatrix] emotion 在beat-x里面是没了吗？beat里面是有的。 (Issue #104)





 
同学你好，BEATX 和 BEAT是一套数据，不同的表现形式，所以beat里面的emotion 标签可以直接在beatx中使用。
