### ISSUE TITLE
论文中的SSAT、TSA分别对应代码中的那些部分？

### ISSUE THREAD

**Issue by Hakeemiang** [PantoMatrix/PantoMatrix#105]
在MAGE_Transformer中似乎并没有SSAT结构？

**Comment by Hakeemiang** [comment]
同时use_word在MAGE_Transformer 的forward过程中没有起到作用，但是在train的过程中修改了该参数

**Comment by H-Liu1997** [comment]
- MAGE_Transformer 中最后使用CNN，节约了更多内存使其能在单张24G显存GPU上运行，性能和使用4层SSAT相似。
- use word的bug已修复
- 更新了 training，inference的 [readme](https://github.com/PantoMatrix/PantoMatrix/blob/main/scripts/EMAGE_2024/readme.md)
