### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: xxxx/22_luqi_0_9_9.npz'

### ISSUE THREAD

**Issue by GuangtaoLyu** [PantoMatrix/PantoMatrix#108]
python scripts/EMAGE_2024/test_demo.py --config ./scripts/EMAGE_2024/configs/emage_test.yaml

I run the script. There is an error. FileNotFoundError: [Errno 2] No such file or directory: xxxx/22_luqi_0_9_9.npz'.

In the test.csv file, it has the filename 22_luqi_0_9_9.npz. but in the data directory, the file 22_luqi_0_9_9.npz missed.

![image](https://github.com/PantoMatrix/PantoMatrix/assets/57834464/e392d580-c828-415e-8940-73fbb2c219b1)

![image](https://github.com/PantoMatrix/PantoMatrix/assets/57834464/34155ab4-50f3-4b90-9a5d-5b981ffa103d)

**Comment by H-Liu1997** [comment]
hi, may I ask does the test.csv you mentioned as same as this?
[train_test_split.csv](https://github.com/PantoMatrix/PantoMatrix/files/14484982/train_test_split.csv)
