### ISSUE TITLE
How to visualize Blendshape coefficient？

### ISSUE THREAD

**Issue by ZiqiaoPeng** [PantoMatrix/PantoMatrix#11]
Hello, thank you for your excellent work!
How do you visualize the Blendshape coefficient? I also want to generate faces like mesh.
In addition, I see that the Blendshape in the dataset has only 51 dimensions, but the Blendshape in the beat.zip you give has 52 dimensions. Have you processed it?
Looking forward to your reply, thanks！

**Comment by H-Liu1997** [comment]
Hi,
1. it's recommend to use iphone's mesh for visualization, refer to [here](https://arkit-face-blendshapes.com/).
2.The number of blendshape weights are 51 as the "dim-52" are netural blendshape. 

I will also share the iphone's mesh later. 
Thanks!
