### ISSUE TITLE
how can i understand the difference of lattent_all and the concatenation of  face, hand, upper, and lower？

### ISSUE THREAD

**Issue by GuangtaoLyu** [PantoMatrix/PantoMatrix#116]
![image](https://github.com/PantoMatrix/PantoMatrix/assets/57834464/ca0a0118-d6c6-46c2-a288-73c7d3997cee)

it seems the latent_all has 337 dims. the concatenation of face, hand, upper, and lower has 335. what is the difference？
i want to know the meaning of per dim. what can i reference?

**Comment by H-Liu1997** [comment]
- face includes 100d flame parameters + 6d jaw pose (it's one joint, represented in rot6d)
- hands, 30  joints, in rot6d, i.e., 30*6=180
- upper, 13 of 16 joints in smplx upper body, except 3 joints:  jaw, left and right eye
- lower, 9 joints + 4d foot contact + 3d global translations, i.e., 7*6+4+3 = 61
- latent all is for all latent related to body, should be 55 joints, 55(upper + hands + lower + jaw + left + right)

**Comment by GuangtaoLyu** [comment]
thank you.



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 12, 2024 01:50 AM
To: ***@***.***&gt;;
Cc: "Guangtao Lyu ( 吕光涛 ***@***.******@***.***&gt;;
Subject: Re: [PantoMatrix/PantoMatrix] how can i understand the difference of lattent_all and the concatenation of  face, hand, upper, and lower？ (Issue #116)




  
face includes 100d flame parameters + 6d jaw pose (it's one joint, represented in rot6d)
 
hands, 30  joints, in rot6d, i.e., 30*6=180
 
upper, 13 of 16 joints in smplx upper body, except 3 joints:  jaw, left and right eye
 
lower, 9 joints + 4d foot contact + 3d global translations, i.e., 7*6+4+3 = 61
 
latent all is for all latent related to body, should be 55 joints, 55(upper + hands + lower + jaw + left + right)
