### ISSUE TITLE
Baseline code release question

### ISSUE THREAD

**Issue by wizardbob** [PantoMatrix/PantoMatrix#12]
Hello, i want to konw will you release the baseline code（like the Audio2gesture）

**Comment by H-Liu1997** [comment]
Hi, thanks for the interest on BEAT dataset.

The script for CaMN is as same as this repo.
we are working on clean up our code for a unified framework to reproduce all baselines performance on BEAT, e.g., CaMN, DisCo, Audio2Gestures, MoGlow, it would take few weeks, sorry for the inconvenience. 

thanks!

**Comment by wizardbob** [comment]
Thank you!
