### ISSUE TITLE
Question about Demo

### ISSUE THREAD

**Issue by cyk990422** [PantoMatrix/PantoMatrix#121]
Hello, Dr. Liu
If I want to use my own synthesized audio to generate gestures, and I provide new wav files and txt files at the same time, how do I need to encode them into conditional embeddings to generate new gestures?

**Comment by H-Liu1997** [comment]
hello! we release a audio only version gradio! you may try it!

https://github.com/PantoMatrix/PantoMatrix/blob/main/scripts/EMAGE_2024/demo.py
