### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [PantoMatrix/PantoMatrix#122]
Hi,
Thank you for releasing this code! Do you have any plans to switch the code license to an open source/OSI-approved license in the future?
Thank you!

**Comment by H-Liu1997** [comment]
I'm sorry, it is not recommend to use it for commerical propose. But you can use it free for non-commerical content creation and sharing. I hope it helps!

Best
Haiyang

**Comment by fakerybakery** [comment]
Makes sense, thank you!
