### ISSUE TITLE
大佬，请教一个问题。我是用EMAGE 通过一段语音生成了对应的肢体运动，如何应用到人物图像上？

### ISSUE THREAD

**Issue by zhanghongyong123456** [PantoMatrix/PantoMatrix#124]
例如：这是根据语音生成对应的驱动视频，如何应用到图片（Stable Diffusion 生成）上，或者说需要图片对应的3D角色，才能驱动
https://pantomatrix.github.io/EMAGE/assets/res/001_V3.mp4
![image](https://github.com/PantoMatrix/PantoMatrix/assets/48466610/be6001a7-0637-4667-90d5-80a33960911c)

**Comment by H-Liu1997** [comment]
hi 我们正在进行视频生成的代码整理，估计下周放出！

**Comment by zhanghongyong123456** [comment]
> hi 我们正在进行视频生成的代码整理，估计下周放出！

期待您视频生成代码，谢谢

**Comment by jiejiedaren** [comment]
I eagerly await the arrival of your video generation code, thank you.

**Comment by jiejiedaren** [comment]
哥，这周大概什么时候能放出呢？

**Comment by jesenzhang** [comment]
> hi 我们正在进行视频生成的代码整理，估计下周放出！

十分期待！

**Comment by zhanghongyong123456** [comment]
> hi 我们正在进行视频生成的代码整理，估计下周放出！

请问大佬驱动图片代码什么时候发布，期待测试

**Comment by sunyclj** [comment]
> hi 我们正在进行视频生成的代码整理，估计下周放出！

请问发布了嘛？

**Comment by H-Liu1997** [comment]
@jiejiedaren @jesenzhang @zhanghongyong123456 @sunyclj  欢迎尝试我们生成视频动作的最新工作 https://huggingface.co/spaces/H-Liu1997/TANGO
