### ISSUE TITLE
Dataset file naming and train/test split problem.

### ISSUE THREAD

**Issue by abcyzj** [PantoMatrix/PantoMatrix#13]
Amazing dataset! I have the following questions.

1. I find that the dataset file naming is a bit confusing. For example, in this name ``1_wayne_0_1_8.bvh``, what are all these numbers' meaning?
2. In the ECCV paper, you mentioned the baseline model was trained on the **4-speaker** data. Can you provide a description of which speakers' data are inlcuded and how do you perform the train/val/test split?

Thank you again for your contribution. Best wishes.

**Comment by H-Liu1997** [comment]
Hi, sorry for the late reply
if we split  `1_wayne_0_1_8.bvh` by `_`

- `1`, `wayne` are speaker ID and name, resprectively. 
- `0` is the recodring type, where `0` English self-talk, `1` English Conversation, `2-3` Chinese, `4-5` Spanish, `6-7` Japanese 
- `1`, `8` are the start and end ID for the sequence, which should be 1-118 for self-talk (1min each) and 1-12 for conversion (10mins each). 

We adopt speakers 2,4,6,8 for training, thanks!

**Comment by abcyzj** [comment]
Thank you for your clarification.
