### ISSUE TITLE
[EMAGE]: Some minor questions about ARKit blendshape coefficient and FLAME expression parameters

### ISSUE THREAD

**Issue by walsvid** [PantoMatrix/PantoMatrix#132]
Hi @H-Liu1997, Thank you very much for the fantastic work. I noticed the transformation matrix W provided in https://github.com/PantoMatrix/PantoMatrix/issues/130, and I have a few questions about W.
1. I would like to ask whether this transformation matrix is ​​constructed based on FLAME2020 or FLAME2023 (or the corresponding SMPLX version) when fitting?
2. Since FLAME later provides the eyelid parameter, does the current transformation matrix W not need to use the eyelid parameter at all?
3. Since the coefficients of arkit will have expressions of eye movement, only the expression + jaw angle can be obtained through W (103 dim output). Does this part still need the participation of eyepose to really get the corresponding expression to match arkit?

In addition, I noticed the meshes (obj file) you released in this issue https://github.com/PantoMatrix/PantoMatrix/issues/123. In the bs folder provided above, `mouthClose.obj` seems very strange, and the mouth area completely exceeds the normal jaw joint angle. May I ask the author what is the reason?

**Comment by H-Liu1997** [comment]
thanks for the question! sorry for the late I just noticed this issue. 

1.  it is FLAME 2020 in SMPLX-FLAME2020,  BTW may I ask what is FLAME2023?
2.  I see, FLAME 2023 maybe an new version decouple the eyelip and general expressions, then you could only use a subset of W, maybe (51-8) * 103 to only focus on general expressions. where 8 is the eyelip related arkit blendshapes. 
3. yes, we need to address eyepose seperatedly
4. it is correct to match jaw open for closing the mouth correctly, you may take a look at [37 mouth close](https://hinzka.hatenablog.com/entry/2021/12/21/222635)

**Comment by walsvid** [comment]
Thank you for your clear explanation.
