### ISSUE TITLE
the Audio and motion is not synchronized in EMAGE data

### ISSUE THREAD

**Issue by gh786137611** [PantoMatrix/PantoMatrix#138]
I visualize data 1_wayne_0_1_1 and 12_zhao_2_1_1 in your published data EMAGE,  and find that the audio is not synchronized with motions.
is it a problem with the published data or  is there something wrong I did?

https://github.com/PantoMatrix/PantoMatrix/assets/13172261/9837260f-0441-4e2b-8edc-660a64b933ee

https://github.com/PantoMatrix/PantoMatrix/assets/13172261/9388601f-bc2a-4ad7-b604-7fa754d3a82c

**Comment by H-Liu1997** [comment]
Let us handle this in issue 137
