### ISSUE TITLE
arkit2flame expression matrix

### ISSUE THREAD

**Issue by adonispeace** [PantoMatrix/PantoMatrix#139]
hi @H-Liu1997 ,thank you for your generous sharing. and i have few questions here.
**1**.  I used it this way and found that it was not converted into the bs corresponding to arkit. Do you have any examples of use? thx！
``` python 
    model = Flame()

    shape = torch.zeros((51, n_shape), dtype=torch.float32)

    # update exp
    M = np.load("models/assets/flame/mat_final.npy")
    exp = np.eye(51)
    arkit_to_flame = exp @ M
    exp_flame = torch.from_numpy(arkit_to_flame[:, :100]).float()
    jaw = torch.from_numpy(arkit_to_flame[:, 100:]).float()

    ret_vals, _ = model(shape, exp_flame, jaw)
```
**2**. why was jawOpen modified into pouting action, instead of just opening the lower jaw(like the effect left)
![image](https://github.com/PantoMatrix/PantoMatrix/assets/30308406/f4f57568-12e7-45e4-af7f-a3d470f8e984)

**Comment by H-Liu1997** [comment]
Thanks for your questions! 
1. It may be the order of bs, you may take a look of order in our released bs and the order in your bs weights

2. As the left one will make the mouth open too much and it is unnatural...

**Comment by adonispeace** [comment]
Thank you for getting back to me
