### ISSUE TITLE
render video problems

### ISSUE THREAD

**Issue by evanxuanzz** [PantoMatrix/PantoMatrix#147]
Sorry for the confusion, i am trying to run the skeleton not the characters. I was able to run the body animation by running the .bvh files (eg. 1_wayne_0_1_8.bvh) of the dataset in blender. I would like to run only the face animation now using the link you had provided in issue #17 (https://drive.google.com/file/d/1LWzwX2PTqXvL75_RJFbss5nMb0epQug0/view), but beat_rendering.py is hanging.

_Originally posted by @akhowling in https://github.com/PantoMatrix/PantoMatrix/issues/29#issuecomment-1874949457_
            
i run into the same problem, how do you fix this?

**Comment by andyl-flwls** [comment]
hi, have you achieved the rendering for characters? May you share some more details of how to do deal with that?
