### ISSUE TITLE
Pretrained Model for FID Evaluation

### ISSUE THREAD

**Issue by JeremyCJM** [PantoMatrix/PantoMatrix#16]
Hi all, could you release the pretrained evaluation network parameters for FID or FGD computation?

**Comment by H-Liu1997** [comment]
hi @JeremyCJM 

you may download the ckpts from [link](https://drive.google.com/drive/folders/1E5lMp0Kc7SV81fJpTiQcOJ3g6Umz6Vtn?usp=sharing),

thanks!

**Comment by bob35buaa** [comment]
> hi @JeremyCJM
> 
> you may download the ckpts from [link](https://drive.google.com/drive/folders/1E5lMp0Kc7SV81fJpTiQcOJ3g6Umz6Vtn?usp=sharing),
> 
> thanks!

Hi Liu, I also want to train the autoencoder on my own dataset for FGD evaluation,  can you share the training scripts? Thanks.
