### ISSUE TITLE
Visualization Code for Pose and Face

### ISSUE THREAD

**Issue by JeremyCJM** [PantoMatrix/PantoMatrix#17]
Hi Haiyang,

Could you share the visualization code for generating the video like the BEAT website: https://pantomatrix.github.io/BEAT/assets/21_ayana_9.mp4

Thanks,
Jeremy

**Comment by H-Liu1997** [comment]
@JeremyCJM 

Happy new year, sorry for the late reply.
1. I uploaded the [visualization code ](https://drive.google.com/file/d/1LWzwX2PTqXvL75_RJFbss5nMb0epQug0/view?usp=share_link) (.blender file) under the same folder as [dataset's download link](https://drive.google.com/drive/folders/1EKuWH8q178QOtFUYaNohdkZbBHQYAmhL?usp=share_link)
2. you may run the facebaker.py on the blender first to initialize the environment. 
3. the script takes `30 FPS, root_offset = 0` motion data as one of inputs, you may refer to30fps.ipynb for that.
4. finally, put the json, bvh, wave under different folders based on the script in the blender, you can render the video like https://pantomatrix.github.io/BEAT/assets/21_ayana_9.mp4 

Thanks!
Haiyang Liu

**Comment by JeremyCJM** [comment]
Hi Haiyang, where is the 30fps.ipynb?

**Comment by JeremyCJM** [comment]
Hi Haiyang,

Thanks for your reply. Could you describe it in more detail? After running the facebaker.py in the blender, then what should be run? To run the beat_rendering.py in blender, I modified the paths in it, but it got stuck for a long time without output. Could you help me with this?

Thanks,
Jeremy
