### ISSUE TITLE
beatV2 maybe not fully aligned

### ISSUE THREAD

**Issue by Ying156209** [PantoMatrix/PantoMatrix#171]
Hi， 
Thank you for providing such a rich dataset. However, I find that motion do not align well with audio, some samples are shown below.

1_wayne_0_72_72 sampling rate 16000, audio_times 62.0, motion_time 60.0
1_wayne_1_2_2 sampling rate 16000, audio_times 683.0, motion_time 661.4333333333333
20_li_0_1_1 sampling rate 16000, audio_times 86.7866875, motion_time 80.2
20_li_1_1_1 sampling rate 16000, audio_times 627.2265625, motion_time 623.6
20_li_1_2_2 sampling rate 16000, audio_times 620.987, motion_time 618.8333333333334
20_li_1_3_3 sampling rate 16000, audio_times 634.06675, motion_time 626.4333333333333
21_ayana_0_16_16 sampling rate 16000, audio_times 93.0, motion_time 89.96666666666667
21_ayana_0_64_64 sampling rate 16000, audio_times 57.0, motion_time 55.333333333333336
21_ayana_0_72_72 sampling rate 16000, audio_times 56.0, motion_time 54.93333333333333
21_ayana_1_11_11 sampling rate 16000, audio_times 593.0, motion_time 590.8333333333334
21_ayana_1_1_1 sampling rate 16000, audio_times 722.121375, motion_time 719.7333333333333
21_ayana_1_2_2 sampling rate 16000, audio_times 612.7454375, motion_time 610.6666666666666
22_luqi_0_104_104 sampling rate 16000, audio_times 81.0, motion_time 79.8
22_luqi_0_74_74 sampling rate 16000, audio_times 69.0, motion_time 66.16666666666667
22_luqi_1_1_1 sampling rate 16000, audio_times 633.7998125, motion_time 631.4666666666667
22_luqi_1_2_2 sampling rate 16000, audio_times 621.8545625, motion_time 619.9333333333333
22_luqi_1_3_3 sampling rate 16000, audio_times 609.7758125, motion_time 608.3333333333334
23_hailing_0_16_16 sampling rate 16000, audio_times 93.0, motion_time 90.43333333333334
23_hailing_0_8_8 sampling rate 16000, audio_times 91.0, motion_time 85.9
23_hailing_1_1_1 sampling rate 16000, audio_times 493.93075, motion_time 484.06666666666666
23_hailing_1_2_2 sampling rate 16000, audio_times 666.0, motion_time 662.2
23_hailing_1_3_3 sampling rate 16000, audio_times 559.0, motion_time 552.5333333333333
24_kexin_0_112_112 sampling rate 16000, audio_times 66.0, motion_time 64.9
24_kexin_0_16_16 sampling rate 16000, audio_times 90.0, motion_time 88.5
24_kexin_0_74_74 sampling rate 16000, audio_times 72.0, motion_time 70.36666666666666
24_kexin_0_8_8 sampling rate 16000, audio_times 85.0, motion_time 81.6

I calculate time duration by 
```
wav, sr = librosa.load(wav16k_file, sr=None)
motion = np.load(motion_file, allow_pickle=True)['poses']
wav_len = wav.shape[0]/float(sr)
mo_len = motion.shape[0]/30.0
```

**Comment by H-Liu1997** [comment]
yes, and thanks for the feedback, the time duration for audio and motion is not same, but the start timing is aligned, you may use the duration of Min(audio_length, motion_length) for each sequence
