### ISSUE TITLE
Dataset usage instructions

### ISSUE THREAD

**Issue by Ying156209** [PantoMatrix/PantoMatrix#18]
Hi, thx for the nice work and dataset!   
Can you please release the scripts to preprocess the raw data to example train/val/test format, or a detailed instruction/Readme for the dataset.
Besides, when will the ongoing smpl-x data be released? Really appreciated that！

**Comment by H-Liu1997** [comment]
Hi, @xuying156209 
Happy new year,
1. I updated the script for preprocess, you may run it under the /dataloader folder. 
2. the smpl or smpl-x version data will be released around 2023/02. 

feel free to let us know If you have any futher concerns,  thanks for your interest in BEAT dataset!

**Comment by H-Liu1997** [comment]
Hi, @Ying156209,

I updated the  detailed instruction/Readme for the dataset. you may check it in the new version readme,

Thanks!
