### ISSUE TITLE
FaceAnimation generation

### ISSUE THREAD

**Issue by nlc1234** [PantoMatrix/PantoMatrix#19]
Final result have only bvh file，where the Blendshape.json file？And how to generate face animation?

**Comment by H-Liu1997** [comment]
hi, as mentioned in our paper, CaMN takes the facial data as one of the
inputs for synthesizing motion data.
We did not synthesize facial data, if you are interested in that you may
build another LSTM+MLP decoder for facial data.

Thanks!
