### ISSUE TITLE
Dataset of other languages

### ISSUE THREAD

**Issue by YaguangGong** [PantoMatrix/PantoMatrix#20]
Hi,
Do you have plans to release data of other languages besides English?

Thanks

**Comment by H-Liu1997** [comment]
hi, @YaguangGong 
Happy new year, 
1. I have not prepare the cut version (the sequences are all in 1 min) for other languages data, 
2. but if you want to use them now, you can download the uncut data (the sequences are in 8 mins) from [beat unzip version](https://drive.google.com/drive/folders/1CVyJOp3G_A9l1N_CsKdHgXQfB4pXhG8c?usp=sharing). 
3. the id with ` 2_x_x, 3_x_x` are Chinese, ` 4_x_x, 5_x_x` are Spanish, ` 6_x_x, 7_x_x` are Japanese

feel free to let us know if you have any further concerns, thanks!

**Comment by YaguangGong** [comment]
Hi, @H-Liu1997 
Thanks for reply. For the id 2_x_x, what do these two x stand for respectively?

**Comment by H-Liu1997** [comment]
hi, 

1_8 is the start and end id for the current sequence, where range is 1-118 for speech and 1-12 for conversation.
for speech section: 0-64 neutral, 65-72 happiness, 73-80 anger, 81-86 sadness, 87-94 contempt, 95-102 surprise, 103-110 fear, 111-118 disgust.

you may check [`./readme.md`](https://github.com/PantoMatrix/BEAT/blob/f4ffee197524076cb705a896b68b4ad237449290/README.md) for more details,

Thanks
