### ISSUE TITLE
Latitude inconsistency occurred in round 19

### ISSUE THREAD

**Issue by yeji0203** [PantoMatrix/PantoMatrix#22]
When I follow the method in Modifiaction, when train reaches round 19, a latitude inconsistency occurs in camn.py
issues:AssertionError: assert(audio_feat_seq.shape[1] == text_feat_seq.shape[1])
audio_feat_seq.size() is torch.Size([1, 164, 128])
text_feat_seq.size() is torch.Size([1, 165, 128])
How can I solve this problem

**Comment by H-Liu1997** [comment]
Hi @yeji0203 

please try to relace the assert (audio_feat.... to 
```python
if (audio_feat_seq.shape[1] != text_feat_seq.shape[1]):
    min_gap = text_feat_seq.shape[1] - audio_feat_seq.shape[1]
    audio_feat_seq = torch.cat((audio_feat_seq, audio_feat_seq[:,-min_gap:, :]),1)
```

**Comment by yeji0203** [comment]
thank you,This problem can be solved
But the new problem is that there are transgressions in several other places, eg:offset_data = pose_data_pre_file[file_content_length] and data_rotation[ori_list[k][1]-v:ori_list[k][1]] = data[iii*3:iii*3+3] in data_tools.py
I dealt with these problems according to my own understanding, but there was no effect, and the final bhv file could not be operated.
Can you give me some help? thank you

**Comment by H-Liu1997** [comment]
hi @yeji0203 
- could you explain more about `transgressions in several other places, eg:offset_data = pose_data_pre_file[file_content_length] and data_rotation[ori_list[k][1]-v:ori_list[k][1]] = data[iii3:iii3+3] in data_tools.py`, sorry I am confused about what is the problem, is it an issue on data preprocessing or?
- I updated the framework and fix the issue of `assert(audio_feat_seq.shape[1] == text_feat_seq.shape[1]`, please try to use the new version code
Thanks!

**Comment by yeji0203** [comment]
sorry,Maybe I didn't make it very clear,In data tools.py, there is a new problem of subscript out of bounds.
At the code of here (for j, line in enumerate(pose_data_pre_file[0:file_content_length]),(offset_data = pose_data_pre_file[file_content_length]) and (ori_lines[file_content_length-2] = 'Frames: ' + str(len(pose_data_file)-1) + '\n).
I found values of (pose_data_pre_file) and (file_content_length) are 429 and 431 respectively when I was debugging.
Other question is valueError: could not broadcast input array from shape (3,) into shape (0,) in the same file,at the code of here (data_rotation[ori_list[k][1]-v:ori_list[k][1]] = data[iii*3:iii*3+3]).
I dealt with these problems according to my own understanding, but there was no effect, and the final bhv file could not be operated.
I don't know if I can make it clear to you.
Can you give me some help? thank you
