### ISSUE TITLE
missing wav json file for speaker 23

### ISSUE THREAD

**Issue by WSPeng** [PantoMatrix/PantoMatrix#24]
According to link https://drive.google.com/drive/folders/11-uu3DCACJ8UwSLS4OZAtz1KnYB9Azam, the wav and json files are missing for Chinese speech part.

**Comment by MengHao666** [comment]
same question

**Comment by H-Liu1997** [comment]
sorry for the late, we release a new version smplx data, and it also contains the missed wav and face data for speaker 23 in Chinese as you mentioned, you can take a look on [the new smplx data](https://drive.google.com/drive/folders/1ukbifhHc85qWTzspEgvAxCXwn9mK4ifr?usp=drive_link)
