### ISSUE TITLE
Seperate files of English data v0.2.1

### ISSUE THREAD

**Issue by 22TonyFStark** [PantoMatrix/PantoMatrix#25]
Hello Liu, happy Chinese New Year~
Thanks for your amazing work! 
I note that files from the link below are slightly different from the v0.2.1 in two ways: 1)without emo and sem; 2)length
[2022/08] [All languages data v0.1.0](https://drive.google.com/drive/folders/1CVyJOp3G_A9l1N_CsKdHgXQfB4pXhG8c?usp=share_link) (in separated files) are available.
Could you provide a separate file of English data v0.2.1(zip files would be great)? I found it difficult for me to download a super large file from google drive due to network limits, so separate zip files may be very helpful.

**Comment by H-Liu1997** [comment]
Thank you and happy Chinese New Year!
I will prepare the separate zip files (4GB each)

**Comment by H-Liu1997** [comment]
hi @22TonyFStark 
you may download the separate files in this [link](https://drive.google.com/drive/folders/15NmITxhKEz90z_Hi928A4W8RdDTzfkp5?usp=share_link) now, thanks!

**Comment by 22TonyFStark** [comment]
> hi @22TonyFStark you may download the separate files in this [link](https://drive.google.com/drive/folders/15NmITxhKEz90z_Hi928A4W8RdDTzfkp5?usp=share_link) now, thanks!

Thanks! It helps a lot!
