### ISSUE TITLE
There is no beat_english_npy in the provided datasets

### ISSUE THREAD

**Issue by aszxnm** [PantoMatrix/PantoMatrix#27]
In the dataloader/preprocessing.py   
ori_data_path_npy='./beat_english_npy'
How do I can this data?

**Comment by BlueP0int** [comment]
The same question,  I just use ```a = librosa.load(sr=16000)``` and ```np.save(a) ```as the annotation writes ``` #wave cache from a = librosa.load(sr=16000) and np.save(a) ``` to store all wav files to the same place of directory beat_english_npy, but I can not guarantee it to be right.

the full code is :
```
for speaker in range(1,31):
    for f in os.listdir(ori_data_path+str(speaker)):
        if(f.endswith('wav')):
            audioOut = os.path.join(ori_data_path_npy+str(speaker), f.replace('wav', 'npy'))
            if(not os.path.exists(audioOut)):
                a, sr = librosa.load(os.path.join(ori_data_path+str(speaker), f), sr=16000)
                np.save(audioOut, a)
```
`ori_data_path` is `XXX/beat_rawdata_english` and `ori_data_path_npy` is `XXX/beat_english_npy`

**Comment by H-Liu1997** [comment]
hi, @BlueP0int @aszxnm  

yeah the `.npy` audio files are just from `librosa.load` and `np.save`, In my case I saved them in advance as we could not install librosa on clould servers. 

Thanks!

**Comment by aszxnm** [comment]
Thanks!

**Comment by aszxnm** [comment]
Thanks! @BlueP0int @H-Liu1997
