### ISSUE TITLE
Face and Gesture Rendering in Blender

### ISSUE THREAD

**Issue by JeremyCJM** [PantoMatrix/PantoMatrix#29]
Hi Haiyang,

Thanks for your reply in #17, but I still cannot render the video successfully. Could you describe it in more detail? After running the facebaker.py in the blender, then what should be run? To run the beat_rendering.py in blender, I modified the paths in it, but it got stuck for a long time without output. Could you help me with this?

Thanks,
Jeremy

**Comment by H-Liu1997** [comment]
hi Jeremy, 

Sorry I just noticed your comments in #17 as it has been closed. Your operation for rendering is correct. we could not reproduce your results so let's check the following things:

- blender version should be < 3.0
- click `window` --> `toggle system console` for a terminal for checking logs
- add print for each step in the function `render_moive` to check which line is running currently or not work well.

**Comment by JeremyCJM** [comment]
Hi Haiyang,

Could you share the code to render such human characters?

![1798b5ba660e6ff6fd606c478d60c12](https://user-images.githubusercontent.com/27879707/228749696-928bc28d-c181-4226-8e13-e28bb1eb649c.png)

Thanks,
Jeremy

**Comment by H-Liu1997** [comment]
hi, sorry for the late reply,

we render this video manually, the detailed steps are explained in #74

thanks!

**Comment by yttehs** [comment]
Hi,

I am trying to render video using blender. But, I am getting the following error:

KeyError: 'bpy_prop_collection[key]: key "Neutral" not found'

It is the function: "assign_facial_animation(animation_data)" that is causing the issue. I see that bpy.data.objects['Neutral'] does not have a 'Neutral' option. It only has 'Camera, 'Cube', and 'Light'.

So I am not able to figure out what is to be done here.

Please could you help me?

**Comment by akhowling** [comment]
Hi Haiyang,
Happy new year!
Im facing the same issue as Jeremy, and I've tried all the trouble shooting methods you have mentioned plus I've tried the process on two different laptops. However, I'm still unable to run beat_rendering.py in blender as it hangs indefinitely as soon as the paths are changed.
Please do let me know how to fix this.
Thank you

**Comment by H-Liu1997** [comment]
> Hi Haiyang, Happy new year! Im facing the same issue as Jeremy, and I've tried all the trouble shooting methods you have mentioned plus I've tried the process on two different laptops. However, I'm still unable to run beat_rendering.py in blender as it hangs indefinitely as soon as the paths are changed. Please do let me know how to fix this. Thank you

happy new year and thanks for your interest in BEAT:), could you share more details, like

- you are tring to render the video like skeletion or chararcters? they are different blender files
![image](https://github.com/PantoMatrix/BEAT/assets/41906591/8419ca00-f835-4203-ac2e-59fe0d0079dc)
![image](https://github.com/PantoMatrix/BEAT/assets/41906591/3c88289a-80e3-4b4a-8b60-ed7cf7417f2f)
- if you are render the video for a skeletion visualization, and you just in the beginning stage of your project, I suggest you take a look of our [new smplx version](https://pantomatrix.github.io/EMAGE/) data. it's eaiser for jointly visualize the face and body.

**Comment by akhowling** [comment]
Sorry for the confusion, i am trying to run the skeleton not the characters. I was able to run the body animation by running the .bvh files (eg. 1_wayne_0_1_8.bvh) of the dataset in blender. I would like to run only the face animation now using the link you had provided in issue #17 (https://drive.google.com/file/d/1LWzwX2PTqXvL75_RJFbss5nMb0epQug0/view), but beat_rendering.py is hanging.

**Comment by yznh228** [comment]
Hi, I would like to ask how the json file of facial movements and bvh file of body movements are visualized into virtual characters with facial movements and body movements in your demo.
![Snipaste_2024-03-15_11-36-24](https://github.com/PantoMatrix/PantoMatrix/assets/102934958/c68b3126-c323-4ecf-aa96-e83de0f6bb80)
