### ISSUE TITLE
How do you control your avatars?

### ISSUE THREAD

**Issue by wubowen416** [PantoMatrix/PantoMatrix#3]
Hi, nice work! Appreciate it that all of the dataset will be released!

You mentioned in your paper that 8 avatars were made using HumanGeneratorV3.
Are these avatars controled by joint euler angle values (or quaternion)? Or do you have scripts to control them by .bvh files?

Will you release your avatars and the controlling sripts in the future?
If you will not, could you please give me a hint on how to control the avatar created by HumanGeneratorV3 using .bvh data?

Thank you very much in advance!

**Comment by SlimeVRX** [comment]
Hi @wubowen416

I'm working on controlling the avatar. I am converting .bvh to SMPL+H / SMPL+X

**Comment by H-Liu1997** [comment]
Hi @wubowen416, sorry for the late reply.  

1. There is an API or button on HumanGeneratorV3 (on Blender) to load a .bvh  file.  Then you may adopt Auto Rig Pro on Blender for rigging to control the avatars.
2. I could share the full body avatar with you if you have purchased the license of  HGv3, but even though you have the same environment as me, you still need to repeat step "1" for loading the new animation.   

Thanks

**Comment by wubowen416** [comment]
Hi @H-Liu1997, thank you for your reply and explanation.

Appreciate that you are going to share your avatar.
I'm planning to purchase HGv3 and Auto-Rig-Pro recently. Could you leave an e-mail address so that I could contact you later for sharing purpose?

**Comment by H-Liu1997** [comment]
@wubowen416 hi, 
we may discuss the sharing by e-mail (liuhaiyang@kmj.iis.u-tokyo.ac.jp). Thanks!

**Comment by wubowen416** [comment]
@H-Liu1997 hi,

I have purchased the HGv3 and Auto-rig-pro in blender and I would like to ask if you could share your avatars to wu.bowen@irl.sys.es.osaka-u.ac.jp.

I was trying to send emails for the verification of my pruchasing to your address but it keeps saying that the address doesn't exist.

**Comment by H-Liu1997** [comment]
@wubowen416 sorry I just noticed that, I will contact you in email, sorry for the late reply
