### ISSUE TITLE
How to convert text or audio file to TextGrid?

### ISSUE THREAD

**Issue by 22TonyFStark** [PantoMatrix/PantoMatrix#30]
Hi Haiyang,
I notice that Chinese version data from this link ([All languages data v0.1.0](https://drive.google.com/drive/folders/1CVyJOp3G_A9l1N_CsKdHgXQfB4pXhG8c?usp=share_link)) does not have TextGrid data. Could you provide them or maybe some tips(code would be great) about converting text or audio file to TextGrid?I think it would be very helpful for training a CaMN model with custom data. 
Zhongfei Qing

**Comment by H-Liu1997** [comment]
hi zhongfei,

we use [Montreal Forced Aligner](https://montreal-forced-aligner.readthedocs.io/en/latest/index.html) for TextGrid. their documents are already well written for getting start. And it is also support different languages.

Thanks!

**Comment by 22TonyFStark** [comment]
@H-Liu1997  Thanks for your time~
