### ISSUE TITLE
How to generate the FacialGenerator?

### ISSUE THREAD

**Issue by nlc1234** [PantoMatrix/PantoMatrix#31]
The structure has PoseGenerator (BodyDecoder and HandDecoder), how to add the facialDecoder ?

**Comment by H-Liu1997** [comment]
You may consider 
- remove the facial encoder
- copy one LSTM and MLP decoder for facial decoding, take the fusion feature (from audio, text, emotional, and id) as input, and change the final linear layer's dimension into 51. 
- add facial reconstruction loss

as a baseline model for facial reconstruction. thanks!

**Comment by nlc1234** [comment]
Thank your answer!
And I have another question, the dataset you provide seems not complete.
When I run build_vocab.py or train.py, the error is always  about dataset(beat_4english_15_141). And I have not download the complete dataset(Englishi data V0.2.1) ,so I do not known the structrue of the dataset.
I can not run the code successfully , cound you give me some suggestions?I will thank you very much!

**Comment by pxcai** [comment]
hi，did you complete this facialGenerator？

**Comment by nlc1234** [comment]
no，I have not , It seems there are so many codes to be updated. And I'm almost messed up.
