### ISSUE TITLE
question about metric detail

### ISSUE THREAD

**Issue by wizardbob** [PantoMatrix/PantoMatrix#33]
Hi, Haiyang. I have two question to trouble you
1. When calculating L1Div and SRGR, which kind of motion data representation should i use to reproduce the paper result, euler angle or position?
2. When calculating alignment, https://github.com/PantoMatrix/BEAT/blob/f4ffee197524076cb705a896b68b4ad237449290/utils/metric.py#L85, here seems downsampling the fps to its half, maybe the original fps is 30 fps(15fps*2)?
Looking forward to your reply!

**Comment by H-Liu1997** [comment]
hi wang, 

1. both L1Div and SRGR are calculated based on euler angle for reproducing the paper result.
2. it may because I used 30fps data to debug the alignment code and didn't remove it, during real inference there is always `without_file=True`.

Thanks!

**Comment by wizardbob** [comment]
Thank you for your reply! Recently i also train my model on Trinity dataset, which is similar to your another work DisCo, when calculate L1Div, the motion data representation is still euler angle? And notice that, the Alignment metric's data range in DisCo is a lot different from BEAT, is there any different setting? Such as sigma, using different joint's beat. 
These questions confuse me, hope you can answer me.

**Comment by H-Liu1997** [comment]
hi, sorry for the late relpy

1. the motion data representation is still euler angle in DisCo paper.
2. The sigma setting for BEAT and Trinity dataset are different, we use 0.3 in BEAT and 2 in DisCo as I remember.

Thanks
