### ISSUE TITLE
The chinese TextGrid

### ISSUE THREAD

**Issue by jiaqiAA** [PantoMatrix/PantoMatrix#34]
Hi,
I notice that Chinese version data from this link ([All languages data v0.1.0](https://drive.google.com/drive/folders/1CVyJOp3G_A9l1N_CsKdHgXQfB4pXhG8c?usp=share_link)) does not have TextGrid data. Could you provide them?
I used [Montreal Forced Aligner](https://montreal-forced-aligner.readthedocs.io/en/latest/index.html) for TextGrid.  It is very slow and may encounter errors while the program is running.
Thanks!

**Comment by H-Liu1997** [comment]
sorry for the late, we release a new version smplx data, and it also contains the textgrid in Chinese as you mentioned, you can take a look on [the new smplx data](https://drive.google.com/drive/folders/1ukbifhHc85qWTzspEgvAxCXwn9mK4ifr?usp=drive_link)
