### ISSUE TITLE
New Comparison Results on the Testset of Dataset v0.2.1

### ISSUE THREAD

**Issue by JeremyCJM** [PantoMatrix/PantoMatrix#35]
Hi Haiyang,

Could you provide the new comparison results on dataset v0.2.1? It seems that the test data was changed according to this issue #28, which means the results in the paper should all be changed.

![image](https://user-images.githubusercontent.com/27879707/219940725-3aca4d9e-adf7-44c9-b85f-f33d787854df.png)

Thanks,
Jeremy

**Comment by H-Liu1997** [comment]
sorry for the late, we release a new version smplx data, and do not plan to update the results for  bvh, you can take a look on [the new smplx data](https://drive.google.com/drive/folders/1ukbifhHc85qWTzspEgvAxCXwn9mK4ifr?usp=drive_link)
