### ISSUE TITLE
How to convert the SMPLX expression parameter into ARKit Face Blendshape weights?

### ISSUE THREAD

**Issue by SlimeVRX** [PantoMatrix/PantoMatrix#36]
Hi!

I have a question, the opposite of the question in this issue #21 

Can you share the code to convert the SMPLX expression parameter into the face Blendshape weights?

I want to learn to do the opposite.

Thank you very much!

**Comment by SlimeVRX** [comment]
Do you have any advice for me on this task?

Thank you very much!

**Comment by H-Liu1997** [comment]
Hi, 

How about directly call ARkit API to process rendered SMPLX facial images/videos?

I'm sorry we have not tested such an opposite function. As ARkit is like a black-box, that is the most simple way from my mind. 

Thanks!

**Comment by SlimeVRX** [comment]
Thank you for your feedback!

I will always follow your work, If you can think of any other way, let me know.

Thank you very much!

**Comment by H-Liu1997** [comment]
thanks for your reply!

I will share the information if I get other ideas, 

now I just close this issue temporally. thanks!
