### ISSUE TITLE
The length of wav and motion bvh is different in beat_english_v0.2.1.

### ISSUE THREAD

**Issue by youngstu** [PantoMatrix/PantoMatrix#37]
For example: 17_itoi_1_3_3.wav

```
 Input #0, wav, from '17_itoi_1_3_3.wav':
  Duration: 00:10:18.32, bitrate: 512 kb/s
    Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 16000 Hz, 1 channels, flt, 512 kb/s
```

10:18.32=618.32second  * 120fps = 74198.4 frame

But 17_itoi_1_3_3.bvh has 72584 frame which is less than wav 74198.4 frame.
```
Frames: 72584
Frame Time: 0.008333
```

**Comment by H-Liu1997** [comment]
Hi, 

you may refer the shorter overlap duration as the correct data.

The difference between bvh and wav is because our annotator manually align the data, it may cut or add some frames for bvh data.

Thanks

**Comment by youngstu** [comment]
It means that the start position for wav and bvh is aligned, and only the longer sequence needs to be truncated at the end?

**Comment by youngstu** [comment]
And is the wav and arkit blendshape weight json aligned and could you introduce the align rule in detail. Very Thanks.

**Comment by H-Liu1997** [comment]
yes. besides, during facial capturing wav and bsw are from the same device
so they are already aligned.

**Comment by youngstu** [comment]
Could you introduce the cut_sequence function in preprocess.ipynb? Is that used to align or other? Thanks.
 
`def cut_sequence(source_path, save_path_a, save_path_b, file_id, fps = 15, sr = 16000, tmp="/home/ma-user/work/datasets/beat_tmp/"):`

**Comment by H-Liu1997** [comment]
yes, 

the scirpt is used for both align and cut a long data (8 mins) into multiple short ones (1 min)
