### ISSUE TITLE
What's the difference for bvh_rot, bvh_rot_vis and bvh_full dataset?

### ISSUE THREAD

**Issue by youngstu** [PantoMatrix/PantoMatrix#39]
What's the difference for bvh_rot, bvh_rot_vis and bvh_full dataset? And which one could be used to train model. Thanks.

**Comment by H-Liu1997** [comment]
hi,

- bvh_rot is the reduced raw data of rotation angles, which is used for training. reduced means: less number of joints, e.g., 47 vs. 75.  
- bvh_rot_vis is raw data + body topology for .bvh format, and padding zero for the data for 75 joints. it is for subjective comparsion.
- bvh full is replacing the padding parts by real ground truth data. it is for the reference.

thanks
