### ISSUE TITLE
Text annotation missing

### ISSUE THREAD

**Issue by Mercurialzhang** [PantoMatrix/PantoMatrix#4]
Thanks for your great job! However, we encountered some problems when using the dataset. We found that the text annotation files are missing in BEAT, where can we download these files? Looking forward to your reply!

**Comment by H-Liu1997** [comment]
Sorry for the late reply, 

You may download the text annotation for English data [here](https://drive.google.com/drive/folders/1CVyJOp3G_A9l1N_CsKdHgXQfB4pXhG8c?usp=share_link), few missed annotations will be updated in this week.

Thank you!
