### ISSUE TITLE
Could you introduce the emotion csv file?

### ISSUE THREAD

**Issue by youngstu** [PantoMatrix/PantoMatrix#40]
Could you introduce the emotion csv file in detail? Thanks.

`.csv for emotion label, 0-7: neutral, happiness, anger, sadness, contempt, surprise, fear, and disgust.
`
Example: 8_catherine_1_9_9.csv
`00_netural,0.0,600,600,0`

**Comment by H-Liu1997** [comment]
hi, 

the key_name of the `00_netural,0.0,600,600,0` is 

1. emotion_class and emotion category name
2. emotion_start_time
3. emotion_end_time
4. duration
5. emotion_class
