### ISSUE TITLE
How to process the data?

### ISSUE THREAD

**Issue by nlc1234** [PantoMatrix/PantoMatrix#41]
Hello,
    When I run preprocessing.ipynb, I always get the error that file not found .npy. Cound you please give me some ideas?

**Comment by H-Liu1997** [comment]
Hi,

The .npy is audio data in numpy array format, which is from librosa.load(audio_file, sr=16000) and np.save(). 
you may consider 

- replace np.load (for audio files) by librosa.load, and make sure the file path for librosa.load is correct.
- or, you could preprocess the audio data by librosa.load and np.save

thanks!

**Comment by nlc1234** [comment]
hi,
Is it the audio average data and audio standard data?
Could you please tell me how to get the audio_mean.npy and audio_std.npy?
thanks!

**Comment by LEELLL** [comment]
I also meet the problem, and I want to know how can I get the "ori_data_path_ann", which named "beat_annotations_english"? Thank you!

**Comment by H-Liu1997** [comment]
> hi, Is it the audio average data and audio standard data? Could you please tell me how to get the audio_mean.npy and audio_std.npy? thanks!

No, the audio's mean and std are calculated and stored using [the fourth block in preprocessing.ipynb](https://github.com/PantoMatrix/BEAT/blob/main/dataloaders/preprocessing.ipynb)

thanks

**Comment by H-Liu1997** [comment]
> I also meet the problem, and I want to know how can I get the "ori_data_path_ann", which named "beat_annotations_english"? Thank you!

you may consider replace `beat_annotations_english` to `beat_rawdata_english` or `beat_english_v0.2.1`.

Before v0.2.1 we adopt seperated path for raw data and annotation, in v0.2.1 we merge these two folders into beat_english_v0.2.1

thanks!
