### ISSUE TITLE
Why is the dimension of face blendshape 51?

### ISSUE THREAD

**Issue by pxcai** [PantoMatrix/PantoMatrix#43]
Hi,haiyang!
Thank you for your fancy work!
I have a question why the face blendshape dimension is 51 in the code, while it is 52 in the paper?And, could you explain how the mapping from .json to vectors works? It is best if you can provide the code! Thanks!

**Comment by H-Liu1997** [comment]
Hi, thanks for your postive comments for our work!

- Iphone's ARKit has 52D, we remove 1D related to tongue motion and use the remained 51D.
- So,  it should be 51 in the paper. I'm sorry for the confusion.

Besides, do you mean how to use the .json data for training? if so, the code is following:
https://github.com/PantoMatrix/BEAT/blob/f4ffee197524076cb705a896b68b4ad237449290/dataloaders/beat.py#L162-L176

**Comment by pxcai** [comment]
> Hi, thanks for your postive comments for our work!
> 
> * Iphone's ARKit has 52D, we remove 1D related to tongue motion and use the remained 51D.
> * So,  it should be 51 in the paper. I'm sorry for the confusion.
> 
> Besides, do you mean how to use the .json data for training? if so, the code is following:
> 
> https://github.com/PantoMatrix/BEAT/blob/f4ffee197524076cb705a896b68b4ad237449290/dataloaders/beat.py#L162-L176

Thank you for your reply, this solves my problem!
