### ISSUE TITLE
The text file for other language

### ISSUE THREAD

**Issue by mrjiangqiao** [PantoMatrix/PantoMatrix#44]
hi,
we want to train a model on the BEAT Chinese sub-set, but we can not find the text file(a txt or a TextGrid) corresponding to the speech file; As we have to have the audio file(.wav) and the text file(.txt or .lab) when we generate the TextGrid file using the [Montreal Forced Aligner](https://montreal-forced-aligner.readthedocs.io/en/latest/index.html), could you please sent us the text file corresponding to these Chinese audio file.
Thanks

**Comment by H-Liu1997** [comment]
hi,
sorry for the inconvience, you could found the Text for Chinese answers from [mocap answers](https://docs.google.com/document/d/1S3wJ64Thu7n5FuAdicSfu4Wt03L0V3d2X6jwIidk_0E/edit?usp=sharing).

Thanks

**Comment by pxcai** [comment]
hi,
we want to train a model on the BEAT Chinese sub-set, we suffer the same problem with you. We don't know how to use text file and speech file to generate the TextGrid file，could you give some advice to us ? 
Thanks

**Comment by Sander-houqi** [comment]
> hi, sorry for the inconvience, you could found the Text for Chinese answers from [mocap answers](https://docs.google.com/document/d/1S3wJ64Thu7n5FuAdicSfu4Wt03L0V3d2X6jwIidk_0E/edit?usp=sharing).
> 
> Thanks

is this link have total chinese text? I found it have missing some text like 12_zhao_3_1_2.wav

**Comment by H-Liu1997** [comment]
sorry for the late, we release a new version smplx data, and it also contains the textgrid in Chinese as you mentioned, you can take a look on [the new smplx data](https://drive.google.com/drive/folders/1ukbifhHc85qWTzspEgvAxCXwn9mK4ifr?usp=drive_link)
