### ISSUE TITLE
How long does it take to train a camn model from scratch？

### ISSUE THREAD

**Issue by LEELLL** [PantoMatrix/PantoMatrix#47]
Hi! How long does it take to train a camn model from scratch？Can I train in Multiple GPUs and how?

**Comment by H-Liu1997** [comment]
hi!

- for CaMN, it takes 2400 mins on 2V100, around 1.5 days. 
- the script supports multiple gpus training, you may consider add `--gpus 0 1` to use 2 gpus, or `--gpus 0 1 2 3` for 4 gpus.

thanks
