### ISSUE TITLE
Dataset License

### ISSUE THREAD

**Issue by SlimeVRX** [PantoMatrix/PantoMatrix#5]
Hi,

Very interesting dataset.
I'm working on converting datasets to Metahuman Unreal. 
But I can't find Dataset License.
Can I share my work?

Thank you very much!

**Comment by H-Liu1997** [comment]
Hi, thank you very much for your additional contribution to the BEAT dataset.
It's fine for any non-commercial usage. 
In my understanding, you are working on converting the dataset by the SMPL model, of course, you can share your work! 
thanks!

**Comment by SlimeVRX** [comment]
Hi,

Yes, I will use the BEAT dataset for academic purposes.

Thank you for your work!
