### ISSUE TITLE
Question about the .npy files in datasets?

### ISSUE THREAD

**Issue by JingyuWu-ZJU** [PantoMatrix/PantoMatrix#50]
An excellent work! 
When I downloaded the v0.21 datasets for English, there is no ".npy" files in the datasets?
So the "preprocessing.ipynb" is going wrong because it can not find the ".npy" files.
There are only TextGird, bvh,csv,json,txt and wav files but I can not find the npy files? 
Thanks

**Comment by JingyuWu-ZJU** [comment]
Is there any link that i can find the npy files?

**Comment by H-Liu1997** [comment]
Hi @JingyuWu-ZJU , thank you for the positive feedback for BEAT dataset.

The `.npy` audio files are  from `librosa.load` and `np.save`, In my case I saved them in advance as we could not install librosa on clould servers.

For more details, you may refer to #27 
Thanks!
