### ISSUE TITLE
Error with the GENEA bvh files

### ISSUE THREAD

**Issue by cjerry1243** [PantoMatrix/PantoMatrix#51]
Thanks for the great work!

I noticed that the motion files are retargeted to the genea skeleton. However, when I downloaded and visualized them, I found some errors. 

First, the fps becomes 24, instead of 30 as the original.
Second, the motion is 5 times slower. (I compared the source and target motion lengths in the same fps)
Third, the genea bvh files are not compatible with the latest genea22 format (https://github.com/TeoNikolov/genea_visualizer). The elbows are twisted.
![image](https://user-images.githubusercontent.com/26675834/227678273-66d0c9bd-f3ac-4e1c-a64b-9aa4d035b2ce.png)

 @zzhat0706

**Comment by zzhat0706** [comment]
Thanks for your interests of BEAT！
We are actually working on fixing the issue 1 & 2.
About issue 3, we only check the skeleton result in Blender. 
Since we are working in SMPL holistic visualization at same time,(include FLAME facial params)
please wait for new version of GENEA skinned version.

**Comment by cjerry1243** [comment]
Thanks for the reply!

We will stay tuned.
