### ISSUE TITLE
How to understand semantic data

### ISSUE THREAD

**Issue by spzhuang** [PantoMatrix/PantoMatrix#53]
Very nice work!
I have load your dataset and study it carefully. It is a doubt  about how to understand the semantic data.
For example:
```
08_metaphoric_l	31.931	34.035	2.104	0.8	love
01_beat_align	34.035	34.577	0.542	0.1
08_metaphoric_l	34.577	35.806	1.229	0.8	beautiful```
Please explation it specifically.

**Comment by H-Liu1997** [comment]
Hi, thank you for the comments for BEAT, 

the columns are gesture_type, start, end, duration, score and key_word.

- gestures types are: no gestures (0), beat gestures (1), low-middle-high quaility deictic gestures (2-3-4), iconic gestures (5-6-7), metaphoric gestures (8-9-10).
- score is based on the gestures type and our consideration of the difficulty for robot to present these gestures.
- keyword is offered by annotators (opinional), it represents which word is more semantic related to the current labeled gestures.

you may watch the sample video from  Semantic Relevancy Annotations in https://pantomatrix.github.io/BEAT/

Thanks

**Comment by leisurehippo** [comment]
Where to download semantic data？I didn't find it in https://drive.google.com/drive/folders/1CVyJOp3G_A9l1N_CsKdHgXQfB4pXhG8c

it only has wav/bvh/json/TextGrid files

**Comment by H-Liu1997** [comment]
> Where to download semantic data？I didn't find it in https://drive.google.com/drive/folders/1CVyJOp3G_A9l1N_CsKdHgXQfB4pXhG8c
> 
> it only has wav/bvh/json/TextGrid files

sorry for the late, we release a new version smplx data, and it also contains the  original semantic data, .txt as you mentioned, you can take a look on [the new smplx data](https://drive.google.com/drive/folders/1ukbifhHc85qWTzspEgvAxCXwn9mK4ifr?usp=drive_link)
