### ISSUE TITLE
Something about Chinese data

### ISSUE THREAD

**Issue by pxcai** [PantoMatrix/PantoMatrix#54]
I found that Chinese data missing .txt file, .TextGrid file and .csv file.How should I get them？

**Comment by H-Liu1997** [comment]
sorry for the late, we release a new version smplx data, and it contains the chinese data, .txt and .textgrid as much as possible as you mentioned, you can take a look on [the new smplx data](https://drive.google.com/drive/folders/1ukbifhHc85qWTzspEgvAxCXwn9mK4ifr?usp=drive_link)
