### ISSUE TITLE
dataloaders/preprocessing.ipynb相关问题咨询

### ISSUE THREAD

**Issue by leisurehippo** [PantoMatrix/PantoMatrix#58]
在使用preprocessing.ipynb时，有如下几个问题：
1. 第三个block里关于bvh文件降采样部分，`if i < 432:`和`if i >= 432:` 是否应该改成`if i < 431:`和`if i >= 431:` 因为bvh文件中431行就已经是MOTION的数据了。`reduced_trainable_bvh.write(trainable_line_data[1:-2]+"\n")`和`reduced_raw_bvh.write(raw_line_data[1:-2]+"\n")`是否应该改成`reduced_trainable_bvh.write(trainable_line_data[2:-1]+"\n")`和`reduced_raw_bvh.write(raw_line_data[2:-1]+"\n")`
2. 在划分train/val/test时，split_rule_english给出的文件名字file_id都是类似1_1,2_2已经划分好的部分，但是原始数据是类似1_8,9_16将几个片段集合在一起。直接运行会报错，请问将原始形如12_zhao_2_1_8.bvh切割成12_zhao_2_1_1.bvh,12_zhao_2_2_2.bvh,...的代码能否给出？
3. 一个小问题，在最后一个block里`endwith.append(os.listdir(default_path+"/"+folder)[500].split(".")[-1])`中的500是不是应该改成0？

**Comment by H-Liu1997** [comment]
谢谢同学的问题和建议！

1. 是的应该是431. 
2. 英语数据是切好的，中文数据目前还没有切成一分钟的小段。所以只有八分钟的版本。论文在划分train/val/test时候只用了英文的数据。如果想测试中文的数据，可以自己针对八分钟的版本进行训练划分。
3. 这个是为了防止读到.ipynb 之类的python cache 后缀，所以取得500
