### ISSUE TITLE
process the raw data

### ISSUE THREAD

**Issue by zyhbili** [PantoMatrix/PantoMatrix#6]
Appreciate for the amazing dataset! 
I found the tool to process the toy dataset. For further research and a fair comparison, would you provide the scripts and the train test split to process the raw data as in the paper.
Whether the self_vae_128/256.bin provided train on the whole training set or just on the toy dataset. Can i use it to compute the fgd? Looking forward to the checkpoint of CaMN!

**Comment by zyhbili** [comment]
And the sem and emo annotations seem missing in the raw data.

**Comment by H-Liu1997** [comment]
Hi @zyhbili, thanks for your interest in BEAT dataset. 
1. you may access the sem and emo annotations from this [url](https://drive.google.com/drive/folders/1EKuWH8q178QOtFUYaNohdkZbBHQYAmhL?usp=share_link). annotations for few sequences are missed, our annotation team will process them by Dec.
2. we are working on clean up our code for a unified framework to reproduce all baselines performance on BEAT, e.g., CaMN, Audio2Gestures, MoGlow, it would take few weeks, sorry for the inconvenience. The script for CaMN is as same as this repo.
3. it's pretrained on toy_data, but you could calculate FGD based on your pretrained model. 
4. for speakers with 4h data, we use the seq 1-8, 65, 73, 81, 87, 95, 103, 111, conversation 1 for test, seq 56-64, 72, 80, 86, 94, 102, 110, 118, conversation 12 as val, the remain data for training. For speakers with 1h data, we use seq 1-2, first half of (65, 73, 81, 87, 95, 103, 111, conversation 1) for test, seq 3-4, second half of (65, 73, 81, 87, 95, 103, 111, conversation 1) for val.

**Comment by JeremyCJM** [comment]
Hi Haiyang, 

I have checked the emo and sem annotation in your provided [url](https://drive.google.com/drive/folders/1EKuWH8q178QOtFUYaNohdkZbBHQYAmhL?usp=share_link). It seems that they have different syntax with the example [data.zip](https://drive.google.com/file/d/1bHiOi7UQwoCZ3sMuzDtBJII8nLVE-csa/view?usp=sharing). Could you help look into this issue?

Thanks,
Jeremy
