### ISSUE TITLE
测试结果异常

### ISSUE THREAD

**Issue by dyang-uestc** [PantoMatrix/PantoMatrix#62]
我使用提供的模型进行测试，e_path: ae_300_all_data_v0.2.1.bin和test_ckpt: camn.bin，但是得到得结果似乎不太对，数据我使用是beat_english_v0.2.1.zip, 想问下有什么建议嘛，感谢您的工作

align score: 0.7506608643262067
srgr score: 0.1260570527286101
l1div score: 2444.087469127046
fid score: 3166.4966574497703

**Comment by H-Liu1997** [comment]
感谢提问，可能是数据版本的问题，请参考 #28

**Comment by dyang-uestc** [comment]
所以说提供的camn.bin或者ae_300_all_data_v0.2.1跟beat_english_v0.2.1版本的数据是对不上的嘛？感谢您的回复

**Comment by dyang-uestc** [comment]
#28这个问题我也看了，ae_300_all_data_v0.2.1是使用beat_english_v0.2.1.zip数据训练得到的，但是camn.bin是使用beat_english_v0.2.1.zip数据得到的么？

**Comment by H-Liu1997** [comment]
你好，

Colab 中的camn.bin 是用v0.2.0 得到的，所以在v0.2.1上测试会有问题。
