### ISSUE TITLE
write wrong line data to .bvh in preprocessing

### ISSUE THREAD

**Issue by huliangxiao** [PantoMatrix/PantoMatrix#64]
codes bellow:
                                        trainable_line_data = np.array2string(trainable_rotation, max_line_width=np.inf, precision=6, suppress_small=False, separator=' ')
                                        **reduced_trainable_bvh.write(trainable_line_data[1:-2]+"\n")**
                                        data_rotation = np.zeros((1))   
                                        for k, v in target_list.items():
                                            data_rotation = np.concatenate((data_rotation, data[ori_list[k][1]-v:ori_list[k][1]]))                             
                                            raw_line_data = np.array2string(data_rotation[1:], max_line_width=np.inf, precision=6, suppress_small=False, separator=' ')
                                        **reduced_raw_bvh.write(raw_line_data[1:-2]+"\n")**

the bold code should advise as 
reduced_trainable_bvh.write(trainable_line_data[1:-1]+"\n")
reduced_raw_bvh.write(raw_line_data[1:-1]+"\n")
or the last value is missing

and
                              if i < 432: 
                                    reduced_full_bvh.write(line_data)
                                    reduced_trainable_bvh.write(line_data)
                                if i >= 432:
                                    data = np.fromstring(line_data, dtype=float, sep=' ')

I think the number 432 should be modified to 431

**Comment by MengHao666** [comment]
> codes bellow: trainable_line_data = np.array2string(trainable_rotation, max_line_width=np.inf, precision=6, suppress_small=False, separator=' ') **reduced_trainable_bvh.write(trainable_line_data[1:-2]+"\n")** data_rotation = np.zeros((1)) for k, v in target_list.items(): data_rotation = np.concatenate((data_rotation, data[ori_list[k][1]-v:ori_list[k][1]])) raw_line_data = np.array2string(data_rotation[1:], max_line_width=np.inf, precision=6, suppress_small=False, separator=' ') **reduced_raw_bvh.write(raw_line_data[1:-2]+"\n")**
> 
> the bold code should advise as reduced_trainable_bvh.write(trainable_line_data[1:-1]+"\n") reduced_raw_bvh.write(raw_line_data[1:-1]+"\n") or the last value is missing
> 
> and if i < 432: reduced_full_bvh.write(line_data) reduced_trainable_bvh.write(line_data) if i >= 432: data = np.fromstring(line_data, dtype=float, sep=' ')
> 
> I think the number 432 should be modified to 431

I also think so. Have you find any dramatic effects due to such small error?

**Comment by H-Liu1997** [comment]
hi, thank you very much for your feedback.

I fixed the number 432 to 431 in preprocessing.ipynb, thanks!
