### ISSUE TITLE
Please share the processed training and test dataset after running preprocessing.ipynb 

### ISSUE THREAD

**Issue by Dean-UQ** [PantoMatrix/PantoMatrix#66]
Hi,
  Can you directly upload the processed official training and test dataset files after running preprocessing.ipynb script. 
  Thanks.

**Comment by H-Liu1997** [comment]
hello, our new version code make it faster to build cache from the source data, you can download the data from [here](https://pantomatrix.github.io/EMAGE/) and check the [new dataloader](https://github.com/PantoMatrix/BEAT/blob/main/scripts/EMAGE_2024/dataloaders/beat_smplx2020.py)
