### ISSUE TITLE
渲染出的视频效果不佳

### ISSUE THREAD

**Issue by QyDing02** [PantoMatrix/PantoMatrix#67]
感谢您的工作！

下面是我试图可视化结果的过程：
### 代码：
我采用了`rendervideo.zip`中的`data2video.blender`文件内的`rendervideo/beat_rendering.py`代码，只将MEAN_DIR变量更改为我的`b4_json_rename`的绝对路径，代码的其他部分保持不变。

#### bvh文件：
我成功按照README，运行`python test.py -c ./configs/camn_4english_15_141.yaml`。在`outputs/audio2pose/custom/[date]_[time]_camn_beat_4english_15_141/9999`目录下，我得到`res_6_carla_0_1_1.bvh`\~`res_6_carla_0_8_8.bvh`八个文件，我把它们重命名为`6_carla_0_1_1.bvh`\~`6_carla_0_8_8.bvh`（也就是去掉res_），将得到新的8个.bvh文件，放在`rendervideo/b6_correct_no_root`目录下。
#### wav文件：
在原始数据集的`beat_english_v0.2.1/6/`目录下，选择`6_carla_0_1_1.wav`\~`6_carla_0_8_8.wav`八个文件，放在`rendervideo/b2_wave_rename`目录下。
#### json文件：
在原始数据集的`beat_english_v0.2.1/6/`目录下，选择`6_carla_0_1_1.json`\~`6_carla_0_8_8.json`八个文件，放在`rendervideo/b4_json_rename`目录下。

### 渲染结果：
在blender按运行脚本的小三角键，等待程序运行一段时间后，在`rendervideo\output_video`目录下得到了`6_carla_0_1_1.mp4`\~`6_carla_0_8_8.mp4`8个文件。

下图是其中一个视频文件的截图（所有的8个视频文件都有同样的问题）：
![image](https://github.com/PantoMatrix/BEAT/assets/64630300/465768c2-07f9-4a2e-ad12-ce48b3964f31)
视频（经过简单压缩处理）：
https://github.com/PantoMatrix/BEAT/assets/64630300/350fb003-f56f-42b5-868d-b53b3ca73c8c

### 在我渲染的视频中出现的一些异常：
1.下肢几乎不动，只能看到脊椎在动
2.模型摆放的位置不对，几乎看不到上半身

请问我应该如何解决这些问题？

**Comment by QyDing02** [comment]
我在`data2video.blender`文件内的`beat_rendering.py`添加了下面两行代码更改了视角：
```
camera = bpy.data.objects['Camera']
camera.data.lens = 35
```
就可以看清人的全貌了：

https://github.com/PantoMatrix/BEAT/assets/64630300/36141b3e-4d64-4dfd-a5a7-39ab2a8489e3


#### 我认为渲染的视频仍然存在以下的问题：
1.人的朝向不对，感觉人像是背向摄像机
2.在视频播放到大约30s的时候，手势就不动了

#### 请问：
1.如何修改blender配置或代码，以改变模型摆放的位置和朝向？
2.如何解决生成的手势只有前30s的问题？

**Comment by H-Liu1997** [comment]
hi，

1. 结果是只有上半身的，我们没有生成下半身的动作
2. 手的朝向的问题是因为我们的checkpoint是在v0.2.0上训练的，而你的测试数据集是v0.2.1, 可以在speaker 1上面做可视化试试。
3. 30s 是不是fps的问题，生成的动作是15fps

**Comment by GuangtaoLyu** [comment]
> hi，
> 
> 1. 结果是只有上半身的，我们没有生成下半身的动作
> 2. 手的朝向的问题是因为我们的checkpoint是在v0.2.0上训练的，而你的测试数据集是v0.2.1, 可以在speaker 1上面做可视化试试。
> 3. 30s 是不是fps的问题，生成的动作是15fps

原来是没生成下半身，怪不得下半身不动。 

那有什么办法能改成升成全身动的吗？

**Comment by GuangtaoLyu** [comment]
> hi，
> 
> 1. 结果是只有上半身的，我们没有生成下半身的动作
> 2. 手的朝向的问题是因为我们的checkpoint是在v0.2.0上训练的，而你的测试数据集是v0.2.1, 可以在speaker 1上面做可视化试试。
> 3. 30s 是不是fps的问题，生成的动作是15fps


我从头训练了一个vae，解码出来的也是只有上半身。 刚入门，能麻烦指个路吗，大概需要改动哪里。

**Comment by H-Liu1997** [comment]
我们的新项目支持全身，[代码，数据已经放出](https://pantomatrix.github.io/EMAGE/)
