### ISSUE TITLE
inference time

### ISSUE THREAD

**Issue by liushengtong-nreal** [PantoMatrix/PantoMatrix#68]
I didn't find an introduction to reasoning time in the paper. Can it achieve real-time voice driving? Refers to speaking while driving gestures.
How about inference speed if it is on CPU?

**Comment by H-Liu1997** [comment]
hi, thanks for the comments,

the camn cant run real-time as it adopt bi-directional LSTM, it must know all audio in advance. It will take 0.7s to process 10s 
motion on NVIDIA 2080Ti.

we have not tested it on CPU.
