### ISSUE TITLE
I need a mesh file in T-pose

### ISSUE THREAD

**Issue by SlimeVRX** [PantoMatrix/PantoMatrix#7]
Hi,

I want to convert dataset to Unreal, but Unreal doesn't allow to import skeleton file without mesh

Can you share me an FBX file that contains mesh (HumanGeneratorV3) in T-pose (like picture)

![image](https://user-images.githubusercontent.com/99313947/202355922-f613a19c-5240-42ab-926a-9ee457dc8a85.png)

Thank you!

**Comment by SlimeVRX** [comment]
I read in humgen3d license: "the 3D models and textures included in Human Generator cannot be shared in easily extractable form (i.e. fbx, blend etc.) even if they are modified and/or applied"

Is there any way can share me a skeleton including mesh?

**Comment by SlimeVRX** [comment]
Sorry, I think my problem is not with the HumanGeneratorV3 mesh. Because the skeleton of HumanGeneratorV3 is not the same as the skeleton in .bvh

**Comment by SlimeVRX** [comment]
Hi @H-Liu1997 

There's good news I want to tell you. I transferred the dataset to Unreal.

[Body and Hand Mocap](https://drive.google.com/file/d/1py4-xJyvD_BzSk6RK-0vkctk-qmLJ9LT/view?usp=share_link)

Face Mocap: [Happy](https://drive.google.com/file/d/1mE4HNlj-8Cnuqt0lpXnBfaTr2wPYZpi3/view?usp=sharing), [Fear](https://drive.google.com/file/d/1LUZ6BIUa77T-unELInjd90HhVw52qDiL/view?usp=sharing), [Anger](https://drive.google.com/file/d/1udGU1x6tp_vRtVm5_yIUu21w6-COcbY7/view?usp=sharing)

**Comment by moliq1** [comment]
Hi @SlimeVRX , 
Great jobs. Can your share your approch on how to transfer the bvh animation to UE?

**Comment by SlimeVRX** [comment]
Hi @moliq1 

I followed the instructions of this [Video](https://www.youtube.com/watch?v=VuJf3jCEs2o&ab_channel=TrashPraxis)

**Comment by SlimeVRX** [comment]
Here is the video

https://user-images.githubusercontent.com/99313947/228105031-3934b569-5f3b-4c0a-aa02-fd597906c578.mp4

**Comment by moliq1** [comment]
> Here is the video

@SlimeVRX  
It looks really great. I'm struglling with exporting the T-pose & A-pose mesh from maya, as the video suggested. Would you be willing to share your output T-pose and A-pose with me? I would be ever so grateful! Here is my email address: moliq5242@gmail.com

**Comment by SlimeVRX** [comment]
Hi,

Do you have WeChat? You can ask me via WeChat. I will guide you when I have free time

**Comment by kiranchhatre** [comment]
hey @SlimeVRX you're doing a great job by converting it using UE or [SMPL+X](https://github.com/PantoMatrix/BEAT/issues/3#issuecomment-1312825821). I have a few questions regarding that, how can I reach out to you? I don't have WeChat, but probably I can install it?

**Comment by SlimeVRX** [comment]
Hi @kiranchhatre 

You can add me on [Twitter](https://twitter.com/Tn23008624)

**Comment by GuangtaoLyu** [comment]
> 你好
> 
> 你们有微信吗？你可以通过微信问我。有空的时候我会指导你

wei

> Hi,
> 
> Do you have WeChat? You can ask me via WeChat. I will guide you when I have free time

how to get your wechat?
