### ISSUE TITLE
why not clean "preprocessing" code?

### ISSUE THREAD

**Issue by MengHao666** [PantoMatrix/PantoMatrix#70]
the code is some kind of messy and diffcult to read. Could you modify it?

**Comment by H-Liu1997** [comment]
hi, thanks for the comments.

we are working on release BEATv2 by the end of July, it is a smplx version beat, and will update the preprocessing code after that.

**Comment by MengHao666** [comment]
> hi, thanks for the comments.
> 
> we are working on release BEATv2 by the end of July, it is a smplx version beat, and will update the preprocessing code after that.

thanks for reply. Would you aslo consider to clean the .bvh file and release the update version ? Personally, I think bvh skeletion fashion is more professional and valuable.

**Comment by YongtaoGE** [comment]
Hi @H-Liu1997. Thanks for your great work. Has the BEATv2 been released?

**Comment by H-Liu1997** [comment]
Thanks for the interest of EMAGE @YongtaoGe @MengHao666 , we release the readme of EMAGE at:

https://github.com/PantoMatrix/PantoMatrix/blob/main/scripts/EMAGE_2024/readme.md

You could found the pretrained models, training and inference scripts now:)
