### ISSUE TITLE
Different inference result using English data v0.2.1

### ISSUE THREAD

**Issue by xljh0520** [PantoMatrix/PantoMatrix#72]
Hi Haiyang,
I downloaded and preprocessed the English data v0.2.1 from this [link](https://drive.google.com/file/d/1Akf0WgAwuH2fvlWbvNpif4XRqXlpznh9/view). The only difference is that I preprocess the wav audio file by this function.
```
def wav2npy(wav_path, npy_path):
    y, sr = librosa.load(wav_path, sr=16000)
    np.save(npy_path, y.flatten())
    return y.flatten(), sr
```
And then, I downloaded the pretrained checkpoint and ran the inference command `python test.py -c ./configs/camn_beat_4english_15_141.yaml`. However, I obtained very different results.

```
 06-29 13:35:34 | align score: 0.7469288022599498                                                                       
 06-29 13:35:34 | srgr score: 0.12785594869216374
 06-29 13:35:34 | l1div score: 2270.6170932666573
 06-29 13:35:34 | fid score: 509.81430044341505
```
Could you help me with this?

**Comment by H-Liu1997** [comment]
hi thanks for the comments,

could you take a look of #28, it may due to the data version issue.
