### ISSUE TITLE
Does the order of Euler angles have an effect on the evaluation model?

### ISSUE THREAD

**Issue by cyk990422** [PantoMatrix/PantoMatrix#78]
I transformed the Euler angle order of xyz in the original Beat bvh file to zyx order, can I still use the evaluation model you gave to evaluate FGD? Or do I need to retrain a model myself?

**Comment by H-Liu1997** [comment]
yes, you have to retrain a model with zyx order to evaluate FGD, as the input of FGD autoencoder is euler angle.
