### ISSUE TITLE
Details about the code when calculating the SRGR

### ISSUE THREAD

**Issue by QyDing02** [PantoMatrix/PantoMatrix#79]
https://github.com/PantoMatrix/BEAT/blob/aeb7c91b079ddd5cedf1d16d4aa500430ad5b00e/utils/metric.py#L42C51-L42C51

I would like to know how the value of 0.165 was calculated to get it? Is it related to the value of `self.pose_dimes` or something else?

**Comment by H-Liu1997** [comment]
0.165 is from the pre-calculated average joint distance to normalize the srgr to 0-1.
