### ISSUE TITLE
How to build a new test cases?

### ISSUE THREAD

**Issue by LEELLL** [PantoMatrix/PantoMatrix#8]
Nice work, and how can I test the model?

**Comment by H-Liu1997** [comment]
Hi @LEELLL 

sorry for the late reply, you may download the ckpts from [this link](https://drive.google.com/drive/folders/1E5lMp0Kc7SV81fJpTiQcOJ3g6Umz6Vtn?usp=sharing),
and I updated the readme for test directly from ckpts.

Thanks!

**Comment by H-Liu1997** [comment]
Hi @LEELLL 

Our [Colab inference script](https://colab.research.google.com/drive/1bB3LqAzceNTW2urXeMpOTPoJYTRoKlzB?usp=sharing) is available, please consider to try it for new test cases!

Thanks!
