### ISSUE TITLE
模型能够处理的时间序列长度是多少

### ISSUE THREAD

**Issue by Droliven** [PantoMatrix/PantoMatrix#86]
请问CCaMN预训练模型所处理的时间序列长度是多少？在训练过程中，输入多少秒的多模态音频、文本等数据生成姿态？在测试过程中，可以输入多少秒的音频生成姿态？

**Comment by H-Liu1997** [comment]
训练使用2.2s 测试能支持无限长度的音频。在1-2分钟的范围内性能都还可以。
