### ISSUE TITLE
how to use the new dataset beat_english_v0.2.1 ?

### ISSUE THREAD

**Issue by GuangtaoLyu** [PantoMatrix/PantoMatrix#87]
Thank you for your great work.

i have downloaded the data beat_english_v0.2.1. how to use it ?   
![image](https://github.com/PantoMatrix/BEAT/assets/57834464/825b94a3-092a-409e-9fee-3c3f6e19718b)

where are the paths beat_english_npy,  beat_cache and  beat_annotations_english in the preprocess.ipynb ?

![image](https://github.com/PantoMatrix/BEAT/assets/57834464/8e3210c7-a428-404d-863f-0bde829accad)

**Comment by ALittlething** [comment]
请问你解决了这个问题吗
