### ISSUE TITLE
For each different face, the mocap face data doesn't show the right emotion

### ISSUE THREAD

**Issue by SlimeVRX** [PantoMatrix/PantoMatrix#9]
Hi,

I'm having a problem like this: for each different face, the data face mocap doesn't show the right emotion (look at it blankly)

I want to increase the "intensity" of the expression by varying the intensity of 52 Blendshapes

![image](https://user-images.githubusercontent.com/99313947/202962985-5efe84fc-4118-4ea6-ba60-82c5217a0dcb.png)

Example: "BrowInnerUp" Blendshape is to show forehead wrinkles

Blendshape data has value from 0 -> 1

I will search the max value of "BrowInnerUp". For example, the max all in the dataset is 0.8 which means that if you don't express as much as possible, I will "reshape" again 0->0.8 to 0->1 to enhance

I need to analyze the data, for each emotion usually only a few Blendshapes will decide, and I will only focus on enhancing those Blendshape

That's the original idea, Can you add more? 

Thank you very much!

Best wishes,

Tin Nguyen Thanh

**Comment by SlimeVRX** [comment]
More videos [Link](https://github.com/PantoMatrix/BEAT/issues/7#issuecomment-1320398309)

**Comment by H-Liu1997** [comment]
hi @SlimeVRX 
Thank you very much for the analysis of facial data and transferring the dataset into unreal format.

The limitation of blendweights quaility are from:
1. the limitation of capture device (IPhone) in the terms of number of blendshapes (52) and tracking accuracy.
2. we dont have the reconstrcuted mesh, the mesh we adopt is different with the real speaker.
3. we dont have a personalized blendshape for each speaker. 

We have one addtional idea to enhancing the data.  Take the anger as an example,
1.  you can mannully select several key-frames, and adjust the blendweights with different factors for each blendweight, e.g., multiply 1.2 for "BrowInnerUp". 
2.  adjust this factor by average several key-frames, and adopt this factor for all remain frames.

If you have any further concerns, feel free to discuss here, thanks!
Best wishes, 
Haiyang Liu

**Comment by SlimeVRX** [comment]
Hi, Thank you for your feedback!

Sorry, but I'm not focused on solving this problem right now. I am working with MMD dataset and trying to convert it.
I will give you feedback on the work if the work progressed.

Thank you very much!

**Comment by H-Liu1997** [comment]
Sure, all the best for your current project!
