### ISSUE TITLE
Regarding the order of your ARKit data

### ISSUE THREAD

**Issue by duan348733684** [PantoMatrix/PantoMatrix#90]
The following is the order of ARKit data according to Apple's official documentation.
Is the order of ARKit data in your JSON file like this?

EyeBlinkLeft = 0
EyeLookDownLeft = 1
EyeLookInLeft = 2
EyeLookOutLeft = 3
EyeLookUpLeft = 4
EyeSquintLeft = 5
EyeWideLeft = 6
EyeBlinkRight = 7
EyeLookDownRight = 8
EyeLookInRight = 9
EyeLookOutRight = 10
EyeLookUpRight = 11
EyeSquintRight = 12
EyeWideRight = 13
JawForward = 14
JawLeft = 15
JawRight = 16
JawOpen = 17
MouthClose = 18
MouthFunnel = 19
MouthPucker = 20
MouthLeft = 21
MouthRight = 22
MouthSmileLeft = 23
MouthSmileRight = 24
MouthFrownLeft = 25
MouthFrownRight = 26
MouthDimpleLeft = 27
MouthDimpleRight = 28
MouthStretchLeft = 29
MouthStretchRight = 30
MouthRollLower = 31
MouthRollUpper = 32
MouthShrugLower = 33
MouthShrugUpper = 34
MouthPressLeft = 35
MouthPressRight = 36
MouthLowerDownLeft = 37
MouthLowerDownRight = 38
MouthUpperUpLeft = 39
MouthUpperUpRight = 40
BrowDownLeft = 41
BrowDownRight = 42
BrowInnerUp = 43
BrowOuterUpLeft = 44
BrowOuterUpRight = 45
CheekPuff = 46
CheekSquintLeft = 47
CheekSquintRight = 48
NoseSneerLeft = 49
NoseSneerRight = 50
TongueOut = 51
HeadYaw = 52
HeadPitch = 53
HeadRoll = 54
LeftEyeYaw = 55
LeftEyePitch = 56
LeftEyeRoll = 57
RightEyeYaw = 58
RightEyePitch = 59
RightEyeRoll = 60

**Comment by H-Liu1997** [comment]
not 100% same, the 0-51 is the same, and in our case we dont have the 52-60

**Comment by xjli360** [comment]
hi, Are you sure the mentioned above of the order “arkit 0-51” is consistent with the order of “arkit” in the beat dataset?


> not 100% same, the 0-51 is the same, and in our case we dont have the 52-60

**Comment by Alpe6825** [comment]
> hi, Are you sure the mentioned above of the order “arkit 0-51” is consistent with the order of “arkit” in the beat dataset?
> 
> > not 100% same, the 0-51 is the same, and in our case we dont have the 52-60

I would also be interested in the answer.
