### ISSUE TITLE
On the BEAT website, there are two data download links: "DOWNLOAD(.zip)" and "DOWNLOAD(SEPARATELY)". Are their contents the same?

### ISSUE THREAD

**Issue by ALittlething** [PantoMatrix/PantoMatrix#92]
DOWNLOAD(.zip): https://drive.google.com/drive/folders/1EKuWH8q178QOtFUYaNohdkZbBHQYAmhL
DOWNLOAD(SEPARATELY): https://drive.google.com/drive/folders/1CVyJOp3G_A9l1N_CsKdHgXQfB4pXhG8c

**Comment by H-Liu1997** [comment]
yes, their contents are the same, also, if you are interest in smplx version data for academic, please take a look of [smplx version data](https://pantomatrix.github.io/EMAGE/)
