### ISSUE TITLE
Incorrect "frametime" in some BVH files

### ISSUE THREAD

**Issue by ChengyuanYan** [PantoMatrix/PantoMatrix#93]
I was debugging some model failures and noticed that "Frame Time" seemed to be wrong in some BVH files.

For example, in `<beat_english_v0.2.1>/29/29_hanieh_1_4_4.bvh`,  lines 430~431 read
```
Frames: 31779                                                                   
Frame Time: 0.041667   
```
which suggests that motion was captured at 24 fps, for a total of 1324.1 seconds

However, there are only 4205801 frames in the corresponding audio (`<beat_english_v0.2.1>/29/29_hanieh_1_4_4.wav`), which, assuming 16000 Hz sampling rate, is 262.8 seconds.

I could think of 2 possible explanations
a) the actual session was ~260 seconds, and the motion was indeed captured at 24 fps; the motion capture kept recording ~1000 seconds after audio capture stopped, as described in #37 
b) the actual session was ~260 seconds, and the motion was actually captured at 120 fps (264.8 seconds); there was a bug in the motion capture system that mis-recorded "Frame Time".

Judging from visualization of said BVH files, and the fact that 120 fps was assumed for all BHV files in `preprocessing.ipynb`, b) feels more likely the case

**Comment by H-Liu1997** [comment]
thanks for your comment and sorry for the late feedback, 

the (b) of your consideration is correct, thanks!

- b) the actual session was ~260 seconds, and the motion was actually captured at 120 fps (264.8 seconds); there was a bug in the motion capture system that mis-recorded "Frame Time".
