### ISSUE TITLE
Indicator issues

### ISSUE THREAD

**Issue by kruaxdk** [PantoMatrix/PantoMatrix#95]
I used the pretrained model weights ae_300.bin and camn.bin that you supplied in the [test.py](http://test.py/) file. The FID is 391.66, SRGR is 0.151, and align is 0.817. There are some discrepancies compared to the metrics provided in the paper, which seems strange to me. Please provide some clarification. Thank you.
![Uploading 2023-12-08 16-58-14屏幕截图.png…]()

**Comment by H-Liu1997** [comment]
hello, have you still suffer this issue? I have several suggestions,

1. take a look of other related issue for reproduction, #28
2. check [colab](https://colab.research.google.com/drive/1bB3LqAzceNTW2urXeMpOTPoJYTRoKlzB?usp=sharing) for debug
3. using our new project  [new smplx version](https://pantomatrix.github.io/EMAGE/)
