### ISSUE TITLE
beat2smpl.py: RuntimeError: Error: Object 'SMPLX-mesh-male' can't be selected because it is not in View Layer 'View Layer'!

### ISSUE THREAD

**Issue by wubowen416** [PantoMatrix/PantoMatrix#96]
Hi Liu,

I am trying to render SMPL fbx files according to your code.

For creating fbx files, there is a loop, iterating over all bvh files.
In the first iteration, it works normally. But in the second iteration, there is a runtime error:
```RuntimeError: Error: Object 'SMPLX-mesh-male' can't be selected because it is not in View Layer 'View Layer'!```.

I tested a little bit, and found that if the ```purge_orphants``` function is not called, this error will disappear.

From this, I think maybe some objects are unintentionally deleted during the process. So I look at the code for creating SMPL-X object in blender which is ```bpy.ops.scene.smplx_add_gender()```, navigating to ```__init__.py``` of smplx_blender_addon, the line that creates the SMPL-X object should be ```bpy.ops.wm.append(filename=object_name, directory=str(objects_path))```.

I tested if this is working normally using the following code:
```
print("object_name before append:", object_name)
bpy.ops.wm.append(filename=object_name, directory=str(objects_path))
print("object_name before select:", object_name)
object_name = context.selected_objects[0].name
print("object_name:", object_name)
```
I found that, in the first iteration, the selected object, i.e., the last printed was ```objective_name: SMPLX-mesh-male```.
However, in the second iteration, the last printed was ```object_name: SMPLX-male```, which is different from the first iteration.
Based on this, I checked the objects in blender and found that in the second iteration, the mesh was not successfully created.
I think this is the problem.

To understand the reason for this problem, I noticed that in the second duration, after ```bpy.ops.wm.append(filename=object_name, directory=str(objects_path))``` is executed, there is an error:
```Error: Shapekey KEKey.002 has an invalid 'from' pointer (0000000000000000), it will be deleted```.
I am not sure but I feel that this indicates the wrong memory is being accessed, so that the mesh object was not successfully created. Due to the fact that commentting out ```purge_orphants``` eliminates the issue, it is likely that smplx package is trying to use pointers it created previously .

Here is the full output in the second iteration:
```
object_name before append: SMPLX-mesh-male
Error: Shapekey KEKey.002 has an invalid 'from' pointer (0000000000000000), it will be deleted
object_name before select: SMPLX-mesh-male
object_name: SMPLX-male
```
and here is output in the first iteration:
```
object_name before append: SMPLX-mesh-male
object_name before select: SMPLX-mesh-male
object_name: SMPLX-mesh-male
```

By the way, I am running it on Windows 11. Maybe it is different from Linux.
Do you know how to solve this problem? Or any workarounds?

This is a bit long, but thanks in advance.

**Comment by H-Liu1997** [comment]
hi, this issue may related to the smplx version data, and you can download the released smplx version data, visualization blender addon from  [new smplx version](https://pantomatrix.github.io/EMAGE/). the code for new model is also available.
