### ISSUE TITLE
Readme for EMAGE

### ISSUE THREAD

**Issue by prinshul** [PantoMatrix/PantoMatrix#99]
Hi, can you please give train/test and data pre-processing Readme for EMAGE. Thanks.

**Comment by r530044129** [comment]
yeah, please, I follow the readme in mian page, 
there is no preprocessing.ipynb in EMAGE in step 5

**Comment by H-Liu1997** [comment]
Thanks for the interest of EMAGE, we release the readme of EMAGE at:

https://github.com/PantoMatrix/PantoMatrix/blob/main/scripts/EMAGE_2024/readme.md

You could found the pretrained models, training and inference scripts now:)
